/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Desktop;
import static java.awt.PageAttributes.MediaType.C;
import javax.swing.ImageIcon;


/**
 *
 * @author devmat
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        botaoLogin = new javax.swing.JButton();
        tituloPagina = new javax.swing.JLabel();
        botaoOcultarSenha = new javax.swing.JButton();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(984, 656));
        setPreferredSize(new java.awt.Dimension(984, 656));

        jPanel1.setMaximumSize(new java.awt.Dimension(984, 656));
        jPanel1.setMinimumSize(new java.awt.Dimension(984, 656));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 340, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 70, 40));

        senha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        senha.setText("Senha");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 60, 30));

        campoSenha.setText("jPasswordField1");
        jPanel1.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 290, 40));

        botaoLogin.setBackground(new java.awt.Color(0, 102, 255));
        botaoLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoLogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoLogin.setText("Login");
        jPanel1.add(botaoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 100, 30));

        tituloPagina.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloPagina.setText("Bem Vindo!");
        jPanel1.add(tituloPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 210, 50));

        botaoOcultarSenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Desktop\\Arquivos_pg_Loja\\ocultar.png")); // NOI18N
        botaoOcultarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOcultarSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoOcultarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 50, 40));

        imagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Desktop\\Design imagem de fundo senai 984x656.png")); // NOI18N
        jPanel1.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed
boolean oculto = true;
    private void botaoOcultarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOcultarSenhaActionPerformed
        // TODO add your handling code here:
         // se senha estiver oculta
        if(oculto==true){
            campoSenha.setEchoChar((char)0);// desocultar senha
            oculto=false;// senha não está mais oculta
            botaoOcultarSenha.setIcon(new ImageIcon("C:/Users/devmat/Documents/NetBeansProjects/Sistema-de-reserva-de-sala-SENAI/ReservaDeSalass/src/main/java/img/mostrar.png"));
        }else{// se a senha não estiver oculta
            campoSenha.setEchoChar('\u2022');// ocultar senha
            oculto=true;// senha oculta novamente
            botaoOcultarSenha.setIcon(new ImageIcon("C:/Users/devmat/Documents/NetBeansProjects/Sistema-de-reserva-de-sala-SENAI/ReservaDeSalass/src/main/java/img/ocultar.png"));
        }// fim do else
    }//GEN-LAST:event_botaoOcultarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton botaoOcultarSenha;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel tituloPagina;
    // End of variables declaration//GEN-END:variables
}
