/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ColaboradorController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Colaborador;

/**
 *
 * @author lldua
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaCadastro() {
        initComponents();
        botaoOcultarSenha.setIcon(new ImageIcon("C:/Users/devmat/Documents/NetBeansProjects/Sistema-de-reserva-de-sala-SENAI/ReservaDeSalass/src/main/java/img/ocultar.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        campoTelefone = new javax.swing.JFormattedTextField();
        nome = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        botaoOcultarSenha = new javax.swing.JButton();
        tituloDapagina = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(984, 656));
        setMinimumSize(new java.awt.Dimension(984, 656));
        setPreferredSize(new java.awt.Dimension(984, 656));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 400, 40));
        jPanel1.add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 400, 40));

        campoSenha.setText("jPasswordField1");
        jPanel1.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 350, 40));

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 400, 40));

        nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nome.setText("NOME:");
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText("E-MAIL:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, 30));

        senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        senha.setText("SENHA:");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 110, 30));

        telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefone.setText("TELEFONE:");
        jPanel1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 30));

        botaoOcultarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mostrar.png"))); // NOI18N
        botaoOcultarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOcultarSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoOcultarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 50, 40));

        tituloDapagina.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDapagina.setText("CADASTRO DE COLABORADOR");
        jPanel1.add(tituloDapagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 370, 40));

        botaoCadastrar.setBackground(new java.awt.Color(51, 51, 255));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 120, 40));

        botaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 120, 40));

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Design imagem de fundo senai 984x656.png"))); // NOI18N
        jPanel1.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean oculto = true;
    private void botaoOcultarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOcultarSenhaActionPerformed
        // TODO add your handling code here:
        if(oculto==true){
            campoSenha.setEchoChar((char)0);// desocultar senha
            oculto=false;// senha não está mais oculta
            botaoOcultarSenha.setIcon(new ImageIcon("C:/Users/devmat/Documents/NetBeansProjects/Sistema-de-reserva-de-sala-SENAI/ReservaDeSalass/src/main/java/img/mostrar.png"));
        }else{// se a senha não estiver oculta
            campoSenha.setEchoChar('\u2022');// ocultar senha
            oculto=true;// senha oculta novamente
            botaoOcultarSenha.setIcon(new ImageIcon("C:/Users/devmat/Documents/NetBeansProjects/Sistema-de-reserva-de-sala-SENAI/ReservaDeSalass/src/main/java/img/ocultar.png"));
        }// fim do else
    }//GEN-LAST:event_botaoOcultarSenhaActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
                try{
        ColaboradorController controller = new ColaboradorController();
        
       
        Colaborador usuario;
                    usuario = new Colaborador(
                            campoNome.getText(),
                            campoEmail.getText(),
                            
                            new String (campoSenha.getPassword()),
                            campoTelefone.getText()
                            
                    );
        controller.cadastrandoColaborador(usuario);
        JOptionPane.showMessageDialog (null,"Colaborador Cadastrado com Sucesso!");
        // Abre a tela de login após cadastrar
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        // fechar tela de cadastro
        dispose();
        
        }catch(Exception e){
          JOptionPane.showMessageDialog(null,"Colaborador Não Cadastrado!"+e);
        }//fim do catch
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOcultarSenha;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JLabel email;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel tituloDapagina;
    // End of variables declaration//GEN-END:variables
}
