/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Colaborador;

/**
 *
 * @author devmat
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public Colaborador usuario;
    public TelaHome(Colaborador colaborador) {
        initComponents();
     usuario = colaborador;
     titulo.setText("Bem-vindo, " + usuario.getNome());
    }

    TelaHome() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaHome = new javax.swing.JPanel();
        botaoCadastroColaborador = new javax.swing.JButton();
        botaoReservaSala = new javax.swing.JButton();
        botaoperfil = new javax.swing.JButton();
        botaoRelatorios1 = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(984, 656));

        TelaHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastroColaborador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastroColaborador.setForeground(new java.awt.Color(51, 51, 51));
        botaoCadastroColaborador.setText("Cadastro de  Colaborador");
        botaoCadastroColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroColaboradorActionPerformed(evt);
            }
        });
        TelaHome.add(botaoCadastroColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 40));

        botaoReservaSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoReservaSala.setForeground(new java.awt.Color(51, 51, 51));
        botaoReservaSala.setText("Reserva de Sala");
        botaoReservaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReservaSalaActionPerformed(evt);
            }
        });
        TelaHome.add(botaoReservaSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 200, 40));

        botaoperfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoperfil.setForeground(new java.awt.Color(51, 51, 51));
        botaoperfil.setText("Perfil do Usuário");
        botaoperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoperfilActionPerformed(evt);
            }
        });
        TelaHome.add(botaoperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 200, 40));

        botaoRelatorios1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRelatorios1.setForeground(new java.awt.Color(51, 51, 51));
        botaoRelatorios1.setText("Relatórios");
        botaoRelatorios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorios1ActionPerformed(evt);
            }
        });
        TelaHome.add(botaoRelatorios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 200, 40));

        botaoSair.setIcon(new javax.swing.ImageIcon("D:\\ProjetosJava\\ReservasalasSenaiImagens\\sair.png")); // NOI18N
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        TelaHome.add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 50, 40));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setText("Bem Vindo!");
        TelaHome.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 210, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Cadastra salas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TelaHome.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 200, 40));

        imagemFundo.setIcon(new javax.swing.ImageIcon("D:\\ProjetosJava\\ReservasalasSenaiImagens\\Design imagem de fundo senai 984x656.png")); // NOI18N
        TelaHome.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TelaHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(
            null, 
            "Deseja realmente sair?", 
            "Confirmação", 
            JOptionPane.OK_CANCEL_OPTION
        );
        
        // Verifica a resposta do usuário
        if (resposta == JOptionPane.OK_OPTION) {
            // Voltar para a tela Home
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
            dispose(); // Fecha a tela atual
        }
        // Caso clique em "Cancelar", nada acontece
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoCadastroColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroColaboradorActionPerformed
        // TODO add your handling code here:
        TelaCadastro cadastro = new TelaCadastro(usuario);
        cadastro.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_botaoCadastroColaboradorActionPerformed

    private void botaoperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoperfilActionPerformed
        // TODO add your handling code here:
       TelaPerfil perfil = new TelaPerfil(usuario);
        perfil.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoperfilActionPerformed

    private void botaoReservaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReservaSalaActionPerformed
        // TODO add your handling code here:
        TelaReserva1 reserva1= new TelaReserva1(usuario);
        reserva1.setVisible(true);
        dispose();
   
    }//GEN-LAST:event_botaoReservaSalaActionPerformed

    private void botaoRelatorios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatorios1ActionPerformed
        // TODO add your handling code here:
        TelaRelatorio1 relatorio1 = new TelaRelatorio1(usuario);
        relatorio1.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoRelatorios1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Telacadastrasalas salas = new Telacadastrasalas(usuario);
        salas.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Colaborador usuario = null;
                new TelaHome(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelaHome;
    private javax.swing.JButton botaoCadastroColaborador;
    private javax.swing.JButton botaoRelatorios1;
    private javax.swing.JButton botaoReservaSala;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoperfil;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
